### ISSUE TITLE
[ubuntu 14.04] xkbcommon-compose.h missing

### ISSUE THREAD

**Issue by TheMikeyR** [shiver/i3lock#3]
Hello, when i'm trying to "make install" I get  a fatal error with missing the package xkbcommon-compose.h. 
I've tried to install libxkbcommon-dev as well as libxkbcommon-x11-dev, but still have the issue. 
after executed make install this happens;
`cc -std=c99 -pipe -Wall -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -D_GNU_SOURCE -DVERSION=\""2.7-9-g59705b0 (2015-12-25)"\"  -c -o i3lock.o i3lock.c
i3lock.c:27:41: fatal error: xkbcommon/xkbcommon-compose.h: No such file or directory
 #include <xkbcommon/xkbcommon-compose.h>
`

**Comment by shiver** [comment]
Hi there,

Sorry for the delayed response. 
This project is actually fairly out of sync with upstream now, and I haven't had much chance to work on it. However, I did manage to get this to compile on an Ubuntu 14.04 by installing the following dependencies:

`sudo apt-get install libxcb1 libxcb-util0 libpam-dev libcairo-dev libxcb-xinerama0 libev-dev libx11-dev libx11-xcb-dev libxkbcommon0 libxkbcommon-x11-dev libxkbcommon-dev libxcb-dpms0-dev libxcb-xinerama0-dev libxkbfile-dev libxcb-util0-dev libxcb-image0-dev`

Let me know if it still gives you problems.

**Comment by TheMikeyR** [comment]
Still no success, I posteed my terminal output after executing the packages you've send and also the error when I try to make.
`$sudo apt-get install libxcb1 libxcb-util0 libpam-dev libcairo-dev libxcb-xinerama0 libev-dev libx11-dev libx11-xcb-dev libxkbcommon0 libxkbcommon-x11-dev libxkbcommon-dev libxcb-dpms0-dev libxcb-xinerama0-dev libxkbfile-dev libxcb-util0-dev libxcb-image0-dev`

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpam0g-dev' instead of 'libpam-dev'
Note, selecting 'libcairo2-dev' instead of 'libcairo-dev'
libx11-dev is already the newest version.
libx11-xcb-dev is already the newest version.
libxcb-dpms0-dev is already the newest version.
libxcb-image0-dev is already the newest version.
libxcb-util0 is already the newest version.
libxcb-util0-dev is already the newest version.
libxcb-xinerama0 is already the newest version.
libxcb-xinerama0-dev is already the newest version.
libxcb1 is already the newest version.
libxkbcommon-dev is already the newest version.
libxkbcommon-x11-dev is already the newest version.
libxkbcommon0 is already the newest version.
libxkbfile-dev is already the newest version.
libev-dev is already the newest version.
libcairo2-dev is already the newest version.
libpam0g-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

`$ make`

```
cc -std=c99 -pipe -Wall -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12   -D_GNU_SOURCE -DVERSION=\""2.7-9-g59705b0 (2015-12-25)"\"  -c -o i3lock.o i3lock.c
i3lock.c:27:41: fatal error: xkbcommon/xkbcommon-compose.h: No such file or directory
 #include <xkbcommon/xkbcommon-compose.h>
                                         ^
compilation terminated.
make: *** [i3lock.o] Error 1 
```

**Comment by shiver** [comment]
Interesting... can you confirm if the file actually exists on your machine?

```
$ ls -la /usr/include/xkbcommon/xkbcommon-compose.h
-rw-r--r-- 1 root root 15768 Aug  2  2015 /usr/include/xkbcommon/xkbcommon-compose.h
```

I can also confirm that the file is provided by the libxkbcommon-dev package:

```
$ dpkg -S /usr/include/xkbcommon/xkbcommon-compose.h 
libxkbcommon-dev: /usr/include/xkbcommon/xkbcommon-compose.h
```

Perhaps there is a version mismatch?

```
$ dpkg -l |grep -i xkbcommon-dev
ii  libxkbcommon-dev                          0.5.0-1~~trusty2                amd64        library interface to the XKB compiler - development files
```

**Comment by jjmcdn** [comment]
There's definitely differences in what's present in libxcbcommon-dev.  xkbcommon-compose.h only appeared in [March 2015](https://lists.debian.org/debian-x/2015/05/msg00257.html) (admittedly a long time ago, but I'm seeing this on Debian Jessie and I'm not ready to move to Stretch since it hasn't been released yet).

I first tried checking out ef3ef30400150f015695df08780e589c6407e646^ and building that, which seemed to work, but then I thought it should be possible to work around this a bit, so I did just that and created https://github.com/Arcaena/i3lock-color/pull/2 for consideration.

**Comment by shiver** [comment]
@joeythesaint I haven't tried your suggestion, but it seems a possibility for this situation too.

It looks like the reason this works for me is because I have installed the original i3wm and i3lock from their repository, as listed on their site https://i3wm.org/docs/repositories.html.

They also appear to provide more up-to-date versions of libxkbcommon-dev for ubuntu 14.04 (and I would assume Debian too), since version 0.5+ is listed as a requirement for the version this project was a fork of.

The easiest way I can think of getting this to work for both Ubuntu and Debian would be to follow the instructions on the i3wm site:

```
# echo "deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe" >> /etc/apt/sources.list
# apt-get update
# apt-get --allow-unauthenticated install sur5r-keyring
# apt-get update
```

Then ensure you have the latest libxbkcommon-dev installed before trying to compile.
Not exactly the most wonderful of solutions granted, but it _should_ work.

**Comment by TheMikeyR** [comment]
Seems like I don't have the package xkbcommon-compose.h, this might be simple for some people to solve, but I've really tried to narrow it down on how to solve it and couldn't figure it out. Should I execute the lines you posted above? Else could you tell me on how to update xkbcommon-dev ?

`ls -la /usr/include/xkbcommon/`             

```
total 300
drwxr-xr-x  2 root root   4096 Apr 15 15:39 .
drwxr-xr-x 70 root root  12288 Apr 27 10:34 ..
-rw-r--r--  1 root root   4295 Apr 10  2014 xkbcommon-compat.h
-rw-r--r--  1 root root  56258 Apr 10  2014 xkbcommon.h
-rw-r--r--  1 root root 212552 Apr 10  2014 xkbcommon-keysyms.h
-rw-r--r--  1 root root   1718 Apr 10  2014 xkbcommon-names.h
-rw-r--r--  1 root root   6012 Apr 10  2014 xkbcommon-x11.h

```

```
$dpkg -S /usr/include/xkbcommon 
libxkbcommon-x11-dev, libxkbcommon-dev: /usr/include/xkbcommon

```

```
$dpkg -S /usr/include/xkbcommon/xkbcommon-compose.h
dpkg-query: no path found matching pattern /usr/include/xkbcommon/xkbcommon-compose.h

```

```
$dpkg -l | grep -i xkbcommon-dev
ii  libxkbcommon-dev                                      0.4.1-0ubuntu1                                      amd64        library interface to the XKB compiler - development files
```

**Comment by shiver** [comment]
@TheMikeyR yeah, it looks like you have an older version of the libxkbcommon-dev package 0.4.1, and this requires 0.5+.
If you follow the steps in my previous comment that might help you out. It is unfortunately a little more painful than it needs to be since I never really expected it to be run on Ubuntu 14.04.

So in summary, do the following:

```
# echo "deb http://debian.sur5r.net/i3/ $(lsb_release -c -s) universe" >> /etc/apt/sources.list
# apt-get update
# apt-get --allow-unauthenticated install sur5r-keyring
# apt-get update
# apt-get install libxkbcommon-dev
```

And then try running "make" again.

**Comment by TheMikeyR** [comment]
I've took the repository from 16.04 concerning libxkbcommon, so I could get 5.0+, worked fine and could make and make install. 
After that my I3 is going into a lockloop, and I had trouble getting it back, but I don't think it have something to do with i3lock, but more my system. In the weekend I will start from scratch and update to 16.04 and hopefully no problems afterwards, since it have the necessary dependencies :+1: 
Thanks for the help @shiver ! :+1: I solved my issue but hit another wall.

Here is what I did if future ubuntu 14.04 have issues;
`sudo nano /etc/apt/sources.list`
Add following to the bottom of the file and save
`deb http://cz.archive.ubuntu.com/ubuntu xenial main`
`sudo apt-get update`
`sudo apt-get install libxkbcommon-dev`
and now you can make
